repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format --verify-no-changes --include
        types_or: ["c#"]
      - id: eslint
        name: eslint
        language: system
        entry: cd src/App.Client && npm run lint:ci
