name: Build Project
description: Build Lambda Project
inputs:
  project-path:
    required: true
    description: The path to the project to build
  output-directory:
    required: true
    description: The output directory to store assests

runs:
  using: composite
  steps:
    - name: Set Project Name
      id: set-project-name
      run: echo "project-name=$(basename ${{ inputs.project-path }})" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build
      run: dotnet publish ${{ inputs.project-path }} --configuration Release --framework net6.0 --runtime linux-arm64 --no-self-contained
      shell: bash
    - name: Zip
      run: mkdir -p ${{ inputs.output-directory }} && zip -r ${{ inputs.output-directory }}/${{ steps.set-project-name.outputs.project-name }}.zip ${{ inputs.project-path }}/bin/Release/net6.0/publish
      shell: bash
